apiVersion: apps/v1
kind: Deployment
metadata:
    name: go-service-test
spec:
    replicas: 1
    selector:
        matchLabels:
            app: go-docker
    template:
        metadata:
            labels:
                app: go-docker
        spec:
            containers:
            - name: go-svc-test-container
              image: go-docker:latest
              imagePullPolicy: Never
              ports:
              - containerPort: 8080
